// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'menu_item': string;
  'menu_item_active': string;
  'menu_item_text': string;
}
export const cssExports: CssExports;
export default cssExports;
