// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'base': string;
  'container': string;
  'container_content': string;
  'container_header': string;
  'container_header_iconsBlock': string;
  'container_header_iconsBlock_container': string;
  'container_header_label': string;
  'container_isOpen': string;
}
export const cssExports: CssExports;
export default cssExports;
