// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  header: string;
  header_btnBlog: string;
  header_btnBlog_item: string;
}
export const cssExports: CssExports;
export default cssExports;
