// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  base: string;
  container: string;
  container_content: string;
  container_content_language: string;
  container_selectBlock: string;
  container_selectBlock_text: string;
}
export const cssExports: CssExports;
export default cssExports;
