export * from './Internet';
export * from './Logo';
export * from './Call';
export * from './Info';
export * from './Profile';
export * from './Logout';
export * from './House';
export * from './Document';
export * from './Invoice';
export * from './Location';
export * from './Clipboard';
export * from './Chat';
export * from './Help';
export * from './ArrowDown';
export * from './ArrowLeft';
export * from './Reload';
export * from './Building';
export * from './Filter';
// filter и building надо переименовать
